modLoader="javafml" 
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]] 
modId="whatever" 
version="${file.jarVersion}" 
displayName="Whatever" 
logoFile="whatever.png" 
credits="Thanks for this example mod goes to Java" 
authors="Fake_Name131" 
description='''
squishyspag told me to call it whatever so i did
'''
[[dependencies.whatever]] 
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.whatever]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
